version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: affidavit-manager-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: affidavit_user
      POSTGRES_PASSWORD: affidavit_pass
      POSTGRES_DB: affidavit_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U affidavit_user -d affidavit_manager"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: